# This file was auto-generated by Fern from our API Definition.

from .copilot_completion_request_citation_style import CopilotCompletionRequestCitationStyle
from .copilot_completion_request_functions_item import CopilotCompletionRequestFunctionsItem
from .copilot_completion_request_functions_item_trigger import CopilotCompletionRequestFunctionsItemTrigger
from .copilot_completion_request_openai_tts_model import CopilotCompletionRequestOpenaiTtsModel
from .copilot_completion_request_openai_voice_name import CopilotCompletionRequestOpenaiVoiceName
from .copilot_completion_request_response_format_type import CopilotCompletionRequestResponseFormatType
from .copilot_completion_request_sadtalker_settings import CopilotCompletionRequestSadtalkerSettings
from .copilot_completion_request_sadtalker_settings_preprocess import (
    CopilotCompletionRequestSadtalkerSettingsPreprocess,
)
from .copilot_completion_request_translation_model import CopilotCompletionRequestTranslationModel
from .copilot_completion_request_tts_provider import CopilotCompletionRequestTtsProvider

__all__ = [
    "CopilotCompletionRequestCitationStyle",
    "CopilotCompletionRequestFunctionsItem",
    "CopilotCompletionRequestFunctionsItemTrigger",
    "CopilotCompletionRequestOpenaiTtsModel",
    "CopilotCompletionRequestOpenaiVoiceName",
    "CopilotCompletionRequestResponseFormatType",
    "CopilotCompletionRequestSadtalkerSettings",
    "CopilotCompletionRequestSadtalkerSettingsPreprocess",
    "CopilotCompletionRequestTranslationModel",
    "CopilotCompletionRequestTtsProvider",
]
