# This file was auto-generated by Fern from our API Definition.

from .copilot_completion_request_functions_item import CopilotCompletionRequestFunctionsItem
from .copilot_completion_request_functions_item_trigger import CopilotCompletionRequestFunctionsItemTrigger
from .copilot_completion_request_openai_tts_model import CopilotCompletionRequestOpenaiTtsModel
from .copilot_completion_request_openai_voice_name import CopilotCompletionRequestOpenaiVoiceName
from .copilot_completion_request_sadtalker_settings import CopilotCompletionRequestSadtalkerSettings
from .copilot_completion_request_sadtalker_settings_preprocess import (
    CopilotCompletionRequestSadtalkerSettingsPreprocess,
)

__all__ = [
    "CopilotCompletionRequestFunctionsItem",
    "CopilotCompletionRequestFunctionsItemTrigger",
    "CopilotCompletionRequestOpenaiTtsModel",
    "CopilotCompletionRequestOpenaiVoiceName",
    "CopilotCompletionRequestSadtalkerSettings",
    "CopilotCompletionRequestSadtalkerSettingsPreprocess",
]
