# This file was auto-generated by Fern from our API Definition.

from .types import (
    CopilotCompletionRequestCitationStyle,
    CopilotCompletionRequestFunctionsItem,
    CopilotCompletionRequestFunctionsItemTrigger,
    CopilotCompletionRequestOpenaiTtsModel,
    CopilotCompletionRequestOpenaiVoiceName,
    CopilotCompletionRequestResponseFormatType,
    CopilotCompletionRequestSadtalkerSettings,
    CopilotCompletionRequestSadtalkerSettingsPreprocess,
    CopilotCompletionRequestTranslationModel,
    CopilotCompletionRequestTtsProvider,
)

__all__ = [
    "CopilotCompletionRequestCitationStyle",
    "CopilotCompletionRequestFunctionsItem",
    "CopilotCompletionRequestFunctionsItemTrigger",
    "CopilotCompletionRequestOpenaiTtsModel",
    "CopilotCompletionRequestOpenaiVoiceName",
    "CopilotCompletionRequestResponseFormatType",
    "CopilotCompletionRequestSadtalkerSettings",
    "CopilotCompletionRequestSadtalkerSettingsPreprocess",
    "CopilotCompletionRequestTranslationModel",
    "CopilotCompletionRequestTtsProvider",
]
