# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.failed_reponse_model_v2 import FailedReponseModelV2


class InternalServerError(ApiError):
    def __init__(self, body: FailedReponseModelV2):
        super().__init__(status_code=500, body=body)
