# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .asr_page_request_output_format import AsrPageRequestOutputFormat
from .asr_page_request_selected_model import AsrPageRequestSelectedModel
from .asr_page_request_translation_model import AsrPageRequestTranslationModel
from .recipe_function import RecipeFunction
from .run_settings import RunSettings
from .variable_schema import VariableSchema


class AsrPageRequest(UniversalBaseModel):
    functions: typing.Optional[typing.List[RecipeFunction]] = None
    variables: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = pydantic.Field(default=None)
    """
    Schema for variables to be used in the variables input
    """

    documents: typing.List[str]
    selected_model: typing.Optional[AsrPageRequestSelectedModel] = pydantic.Field(default=None)
    """
    Choose a model to transcribe incoming audio messages to text.
    """

    language: typing.Optional[str] = None
    input_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional prompt that the model can use as context to better understand the speech and maintain a consistent writing style.
    """

    translation_model: typing.Optional[AsrPageRequestTranslationModel] = None
    output_format: typing.Optional[AsrPageRequestOutputFormat] = None
    google_translate_target: typing.Optional[str] = pydantic.Field(default=None)
    """
    use `translation_model` & `translation_target` instead.
    """

    translation_source: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is usually inferred from the spoken language, but in case that is set to Auto detect, you can specify one explicitly.
    """

    translation_target: typing.Optional[str] = None
    glossary_document: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provide a glossary to customize translation and improve accuracy of domain-specific terms.
    If not specified or invalid, no glossary will be used. Read about the expected format [here](https://docs.google.com/document/d/1TwzAvFmFYekloRKql2PXNPIyqCbsHRL8ZtnWkzAYrh8/edit?usp=sharing).
    """

    settings: typing.Optional[RunSettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
