# This file was auto-generated by Fern from our API Definition.

import typing

AsrPageRequestTranslationModel = typing.Union[
    typing.Literal["google", "ghana_nlp", "whisper_large_v2", "whisper_large_v3", "seamless_m4t_v2"], typing.Any
]
