# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from .recipe_function import RecipeFunction
from .run_settings import RunSettings


class BulkRunnerPageRequest(pydantic_v1.BaseModel):
    functions: typing.Optional[typing.List[RecipeFunction]] = None
    variables: typing.Optional[typing.Dict[str, typing.Any]] = pydantic_v1.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    documents: typing.List[str] = pydantic_v1.Field()
    """
    Upload or link to a CSV or google sheet that contains your sample input data.
    For example, for Copilot, this would sample questions or for Art QR Code, would would be pairs of image descriptions and URLs.
    Remember to includes header names in your CSV too.
    """

    run_urls: typing.List[str] = pydantic_v1.Field()
    """
    Provide one or more Gooey.AI workflow runs.
    You can add multiple runs from the same recipe (e.g. two versions of your copilot) and we'll run the inputs over both of them.
    """

    input_columns: typing.Dict[str, str] = pydantic_v1.Field()
    """
    For each input field in the Gooey.AI workflow, specify the column in your input data that corresponds to it.
    """

    output_columns: typing.Dict[str, str] = pydantic_v1.Field()
    """
    For each output field in the Gooey.AI workflow, specify the column name that you'd like to use for it in the output data.
    """

    eval_urls: typing.Optional[typing.List[str]] = pydantic_v1.Field(default=None)
    """
    _(optional)_ Add one or more Gooey.AI Evaluator Workflows to evaluate the results of your runs.
    """

    settings: typing.Optional[RunSettings] = None

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
