# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .compare_text2img_page_request_scheduler import CompareText2ImgPageRequestScheduler
from .compare_text2img_page_request_selected_models_item import CompareText2ImgPageRequestSelectedModelsItem
from .lora_weight import LoraWeight
from .recipe_function import RecipeFunction
from .run_settings import RunSettings
from .variable_schema import VariableSchema


class CompareText2ImgPageRequest(UniversalBaseModel):
    functions: typing.Optional[typing.List[RecipeFunction]] = None
    variables: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = pydantic.Field(default=None)
    """
    Schema for variables to be used in the variables input
    """

    text_prompt: str
    negative_prompt: typing.Optional[str] = None
    output_width: typing.Optional[int] = None
    output_height: typing.Optional[int] = None
    num_outputs: typing.Optional[int] = None
    quality: typing.Optional[int] = None
    dall_e3quality: typing.Optional[str] = pydantic.Field(alias="dall_e_3_quality", default=None)
    dall_e3style: typing.Optional[str] = pydantic.Field(alias="dall_e_3_style", default=None)
    guidance_scale: typing.Optional[float] = None
    seed: typing.Optional[int] = None
    sd2upscaling: typing.Optional[bool] = pydantic.Field(alias="sd_2_upscaling", default=None)
    selected_models: typing.Optional[typing.List[CompareText2ImgPageRequestSelectedModelsItem]] = None
    scheduler: typing.Optional[CompareText2ImgPageRequestScheduler] = None
    edit_instruction: typing.Optional[str] = None
    image_guidance_scale: typing.Optional[float] = None
    loras: typing.Optional[typing.List[LoraWeight]] = None
    settings: typing.Optional[RunSettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
