# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .compare_upscaler_page_request_selected_models_item import CompareUpscalerPageRequestSelectedModelsItem
from .recipe_function import RecipeFunction
from .run_settings import RunSettings


class CompareUpscalerPageRequest(UniversalBaseModel):
    functions: typing.Optional[typing.List[RecipeFunction]] = None
    variables: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    input_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Input Image
    """

    input_video: typing.Optional[str] = pydantic.Field(default=None)
    """
    Input Video
    """

    scale: int = pydantic.Field()
    """
    The final upsampling scale of the image
    """

    selected_models: typing.Optional[typing.List[CompareUpscalerPageRequestSelectedModelsItem]] = None
    selected_bg_model: typing.Optional[typing.Literal["real_esrgan_x2"]] = None
    settings: typing.Optional[RunSettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
