# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1


class ConversationStart(pydantic_v1.BaseModel):
    conversation_id: str = pydantic_v1.Field()
    """
    The conversation ID you provided in the request, or a random ID if not provided
    """

    user_id: str = pydantic_v1.Field()
    """
    The user ID associated with this conversation
    """

    user_message_id: str = pydantic_v1.Field()
    """
    The user message ID you provided in the request, or a random ID if not provided.
    """

    bot_message_id: str = pydantic_v1.Field()
    """
    The bot message ID. Use this ID as the `context_msg_id` when sending a `button_pressed`.
    """

    created_at: str = pydantic_v1.Field()
    """
    Time when the conversation was created as ISO format
    """

    type: typing.Optional[str] = pydantic_v1.Field(default=None)
    """
    The conversation was started. Save the IDs for future requests.
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
