# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_url import ImageUrl


class ConversationEntryContentItem_Text(UniversalBaseModel):
    text: typing.Optional[str] = None
    type: typing.Literal["text"] = "text"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConversationEntryContentItem_ImageUrl(UniversalBaseModel):
    image_url: typing.Optional[ImageUrl] = None
    type: typing.Literal["image_url"] = "image_url"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ConversationEntryContentItem = typing.Union[ConversationEntryContentItem_Text, ConversationEntryContentItem_ImageUrl]
