# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .embeddings_page_request_functions_item import EmbeddingsPageRequestFunctionsItem
import pydantic
from .embeddings_page_request_selected_model import EmbeddingsPageRequestSelectedModel
from .run_settings import RunSettings
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class EmbeddingsPageRequest(UniversalBaseModel):
    functions: typing.Optional[typing.List[EmbeddingsPageRequestFunctionsItem]] = None
    variables: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    texts: typing.List[str]
    selected_model: typing.Optional[EmbeddingsPageRequestSelectedModel] = None
    settings: typing.Optional[RunSettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
