# This file was auto-generated by Fern from our API Definition.

import typing

Function = typing.Union[
    typing.Literal[
        "mean",
        "median",
        "min",
        "max",
        "sum",
        "cumsum",
        "prod",
        "cumprod",
        "std",
        "var",
        "first",
        "last",
        "count",
        "cumcount",
        "nunique",
        "rank",
    ],
    typing.Any,
]
