# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flux_lora_fast_inputs import FluxLoraFastInputs
from .model_trainer_page_request_selected_model import ModelTrainerPageRequestSelectedModel
from .recipe_function import RecipeFunction
from .run_settings import RunSettings
from .variable_schema import VariableSchema


class ModelTrainerPageRequest(UniversalBaseModel):
    functions: typing.Optional[typing.List[RecipeFunction]] = None
    variables: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = pydantic.Field(default=None)
    """
    Schema for variables to be used in the variables input
    """

    selected_model: typing.Optional[ModelTrainerPageRequestSelectedModel] = None
    inputs: FluxLoraFastInputs
    learning_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    The learning rate to use for training the model.
    """

    steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of steps to train the model for.
    """

    settings: typing.Optional[RunSettings] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
