# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from .object_inpainting_page_request_selected_model import ObjectInpaintingPageRequestSelectedModel
from .recipe_function import RecipeFunction
from .run_settings import RunSettings


class ObjectInpaintingPageRequest(pydantic_v1.BaseModel):
    functions: typing.Optional[typing.List[RecipeFunction]] = None
    variables: typing.Optional[typing.Dict[str, typing.Any]] = pydantic_v1.Field(default=None)
    """
    Variables to be used as Jinja prompt templates and in functions as arguments
    """

    input_image: str
    text_prompt: str
    obj_scale: typing.Optional[float] = None
    obj_pos_x: typing.Optional[float] = None
    obj_pos_y: typing.Optional[float] = None
    mask_threshold: typing.Optional[float] = None
    selected_model: typing.Optional[ObjectInpaintingPageRequestSelectedModel] = None
    negative_prompt: typing.Optional[str] = None
    num_outputs: typing.Optional[int] = None
    quality: typing.Optional[int] = None
    output_width: typing.Optional[int] = None
    output_height: typing.Optional[int] = None
    guidance_scale: typing.Optional[float] = None
    sd2upscaling: typing.Optional[bool] = pydantic_v1.Field(alias="sd_2_upscaling", default=None)
    seed: typing.Optional[int] = None
    settings: typing.Optional[RunSettings] = None

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
