# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.internal_server_error import InternalServerError
from ..errors.payment_required_error import PaymentRequiredError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.async_api_response_model_v3 import AsyncApiResponseModelV3
from ..types.doc_extract_page_request_response_format_type import DocExtractPageRequestResponseFormatType
from ..types.doc_extract_page_request_selected_asr_model import DocExtractPageRequestSelectedAsrModel
from ..types.doc_extract_page_request_selected_model import DocExtractPageRequestSelectedModel
from ..types.doc_extract_page_request_translation_model import DocExtractPageRequestTranslationModel
from ..types.doc_extract_page_response import DocExtractPageResponse
from ..types.doc_extract_page_status_response import DocExtractPageStatusResponse
from ..types.failed_reponse_model_v2 import FailedReponseModelV2
from ..types.generic_error_response import GenericErrorResponse
from ..types.http_validation_error import HttpValidationError
from ..types.recipe_function import RecipeFunction
from ..types.run_settings import RunSettings
from ..types.variable_schema import VariableSchema

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SyntheticDataMakerForVideosPdFsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def doc_extract(
        self,
        *,
        documents: typing.Sequence[str],
        functions: typing.Optional[typing.Sequence[RecipeFunction]] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = OMIT,
        sheet_url: typing.Optional[str] = OMIT,
        selected_asr_model: typing.Optional[DocExtractPageRequestSelectedAsrModel] = OMIT,
        language: typing.Optional[str] = OMIT,
        translation_model: typing.Optional[DocExtractPageRequestTranslationModel] = OMIT,
        google_translate_target: typing.Optional[str] = OMIT,
        task_instructions: typing.Optional[str] = OMIT,
        selected_model: typing.Optional[DocExtractPageRequestSelectedModel] = OMIT,
        translation_source: typing.Optional[str] = OMIT,
        translation_target: typing.Optional[str] = OMIT,
        glossary_document: typing.Optional[str] = OMIT,
        avoid_repetition: typing.Optional[bool] = OMIT,
        num_outputs: typing.Optional[int] = OMIT,
        quality: typing.Optional[float] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        sampling_temperature: typing.Optional[float] = OMIT,
        response_format_type: typing.Optional[DocExtractPageRequestResponseFormatType] = OMIT,
        settings: typing.Optional[RunSettings] = OMIT,
        request_options: typing.Optional[RequestOptions] = None
    ) -> DocExtractPageResponse:
        """
        Parameters
        ----------
        documents : typing.Sequence[str]

        functions : typing.Optional[typing.Sequence[RecipeFunction]]

        variables : typing.Optional[typing.Dict[str, typing.Any]]
            Variables to be used as Jinja prompt templates and in functions as arguments

        variables_schema : typing.Optional[typing.Dict[str, VariableSchema]]
            Schema for variables to be used in the variables input

        sheet_url : typing.Optional[str]

        selected_asr_model : typing.Optional[DocExtractPageRequestSelectedAsrModel]

        language : typing.Optional[str]

        translation_model : typing.Optional[DocExtractPageRequestTranslationModel]

        google_translate_target : typing.Optional[str]
            use `translation_model` & `translation_target` instead.

        task_instructions : typing.Optional[str]

        selected_model : typing.Optional[DocExtractPageRequestSelectedModel]

        translation_source : typing.Optional[str]
            This is usually inferred from the spoken language, but in case that is set to Auto detect, you can specify one explicitly.

        translation_target : typing.Optional[str]

        glossary_document : typing.Optional[str]
            Provide a glossary to customize translation and improve accuracy of domain-specific terms.
            If not specified or invalid, no glossary will be used. Read about the expected format [here](https://docs.google.com/document/d/1TwzAvFmFYekloRKql2PXNPIyqCbsHRL8ZtnWkzAYrh8/edit?usp=sharing).

        avoid_repetition : typing.Optional[bool]

        num_outputs : typing.Optional[int]

        quality : typing.Optional[float]

        max_tokens : typing.Optional[int]

        sampling_temperature : typing.Optional[float]

        response_format_type : typing.Optional[DocExtractPageRequestResponseFormatType]

        settings : typing.Optional[RunSettings]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocExtractPageResponse
            Successful Response

        Examples
        --------
        from gooey import Gooey

        client = Gooey(
            api_key="YOUR_API_KEY",
        )
        client.synthetic_data_maker_for_videos_pd_fs.doc_extract(
            documents=["documents"],
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/doc-extract",
            method="POST",
            json={
                "functions": functions,
                "variables": variables,
                "variables_schema": variables_schema,
                "documents": documents,
                "sheet_url": sheet_url,
                "selected_asr_model": selected_asr_model,
                "language": language,
                "translation_model": translation_model,
                "google_translate_target": google_translate_target,
                "task_instructions": task_instructions,
                "selected_model": selected_model,
                "translation_source": translation_source,
                "translation_target": translation_target,
                "glossary_document": glossary_document,
                "avoid_repetition": avoid_repetition,
                "num_outputs": num_outputs,
                "quality": quality,
                "max_tokens": max_tokens,
                "sampling_temperature": sampling_temperature,
                "response_format_type": response_format_type,
                "settings": settings,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(DocExtractPageResponse, parse_obj_as(type_=DocExtractPageResponse, object_=_response.json()))  # type: ignore
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(typing.Any, parse_obj_as(type_=typing.Any, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(HttpValidationError, parse_obj_as(type_=HttpValidationError, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(GenericErrorResponse, parse_obj_as(type_=GenericErrorResponse, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(FailedReponseModelV2, parse_obj_as(type_=FailedReponseModelV2, object_=_response.json()))  # type: ignore
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def async_doc_extract(
        self,
        *,
        documents: typing.Sequence[str],
        functions: typing.Optional[typing.Sequence[RecipeFunction]] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = OMIT,
        sheet_url: typing.Optional[str] = OMIT,
        selected_asr_model: typing.Optional[DocExtractPageRequestSelectedAsrModel] = OMIT,
        language: typing.Optional[str] = OMIT,
        translation_model: typing.Optional[DocExtractPageRequestTranslationModel] = OMIT,
        google_translate_target: typing.Optional[str] = OMIT,
        task_instructions: typing.Optional[str] = OMIT,
        selected_model: typing.Optional[DocExtractPageRequestSelectedModel] = OMIT,
        translation_source: typing.Optional[str] = OMIT,
        translation_target: typing.Optional[str] = OMIT,
        glossary_document: typing.Optional[str] = OMIT,
        avoid_repetition: typing.Optional[bool] = OMIT,
        num_outputs: typing.Optional[int] = OMIT,
        quality: typing.Optional[float] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        sampling_temperature: typing.Optional[float] = OMIT,
        response_format_type: typing.Optional[DocExtractPageRequestResponseFormatType] = OMIT,
        settings: typing.Optional[RunSettings] = OMIT,
        request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncApiResponseModelV3:
        """
        Parameters
        ----------
        documents : typing.Sequence[str]

        functions : typing.Optional[typing.Sequence[RecipeFunction]]

        variables : typing.Optional[typing.Dict[str, typing.Any]]
            Variables to be used as Jinja prompt templates and in functions as arguments

        variables_schema : typing.Optional[typing.Dict[str, VariableSchema]]
            Schema for variables to be used in the variables input

        sheet_url : typing.Optional[str]

        selected_asr_model : typing.Optional[DocExtractPageRequestSelectedAsrModel]

        language : typing.Optional[str]

        translation_model : typing.Optional[DocExtractPageRequestTranslationModel]

        google_translate_target : typing.Optional[str]
            use `translation_model` & `translation_target` instead.

        task_instructions : typing.Optional[str]

        selected_model : typing.Optional[DocExtractPageRequestSelectedModel]

        translation_source : typing.Optional[str]
            This is usually inferred from the spoken language, but in case that is set to Auto detect, you can specify one explicitly.

        translation_target : typing.Optional[str]

        glossary_document : typing.Optional[str]
            Provide a glossary to customize translation and improve accuracy of domain-specific terms.
            If not specified or invalid, no glossary will be used. Read about the expected format [here](https://docs.google.com/document/d/1TwzAvFmFYekloRKql2PXNPIyqCbsHRL8ZtnWkzAYrh8/edit?usp=sharing).

        avoid_repetition : typing.Optional[bool]

        num_outputs : typing.Optional[int]

        quality : typing.Optional[float]

        max_tokens : typing.Optional[int]

        sampling_temperature : typing.Optional[float]

        response_format_type : typing.Optional[DocExtractPageRequestResponseFormatType]

        settings : typing.Optional[RunSettings]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncApiResponseModelV3
            Successful Response

        Examples
        --------
        from gooey import Gooey

        client = Gooey(
            api_key="YOUR_API_KEY",
        )
        client.synthetic_data_maker_for_videos_pd_fs.async_doc_extract(
            documents=["documents"],
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v3/doc-extract/async",
            method="POST",
            json={
                "functions": functions,
                "variables": variables,
                "variables_schema": variables_schema,
                "documents": documents,
                "sheet_url": sheet_url,
                "selected_asr_model": selected_asr_model,
                "language": language,
                "translation_model": translation_model,
                "google_translate_target": google_translate_target,
                "task_instructions": task_instructions,
                "selected_model": selected_model,
                "translation_source": translation_source,
                "translation_target": translation_target,
                "glossary_document": glossary_document,
                "avoid_repetition": avoid_repetition,
                "num_outputs": num_outputs,
                "quality": quality,
                "max_tokens": max_tokens,
                "sampling_temperature": sampling_temperature,
                "response_format_type": response_format_type,
                "settings": settings,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(AsyncApiResponseModelV3, parse_obj_as(type_=AsyncApiResponseModelV3, object_=_response.json()))  # type: ignore
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(typing.Any, parse_obj_as(type_=typing.Any, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(HttpValidationError, parse_obj_as(type_=HttpValidationError, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(GenericErrorResponse, parse_obj_as(type_=GenericErrorResponse, object_=_response.json()))  # type: ignore
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def status_doc_extract(
        self, *, run_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DocExtractPageStatusResponse:
        """
        Parameters
        ----------
        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocExtractPageStatusResponse
            Successful Response

        Examples
        --------
        from gooey import Gooey

        client = Gooey(
            api_key="YOUR_API_KEY",
        )
        client.synthetic_data_maker_for_videos_pd_fs.status_doc_extract(
            run_id="run_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v3/doc-extract/status", method="GET", params={"run_id": run_id}, request_options=request_options
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(DocExtractPageStatusResponse, parse_obj_as(type_=DocExtractPageStatusResponse, object_=_response.json()))  # type: ignore
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(typing.Any, parse_obj_as(type_=typing.Any, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(HttpValidationError, parse_obj_as(type_=HttpValidationError, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(GenericErrorResponse, parse_obj_as(type_=GenericErrorResponse, object_=_response.json()))  # type: ignore
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSyntheticDataMakerForVideosPdFsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def doc_extract(
        self,
        *,
        documents: typing.Sequence[str],
        functions: typing.Optional[typing.Sequence[RecipeFunction]] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = OMIT,
        sheet_url: typing.Optional[str] = OMIT,
        selected_asr_model: typing.Optional[DocExtractPageRequestSelectedAsrModel] = OMIT,
        language: typing.Optional[str] = OMIT,
        translation_model: typing.Optional[DocExtractPageRequestTranslationModel] = OMIT,
        google_translate_target: typing.Optional[str] = OMIT,
        task_instructions: typing.Optional[str] = OMIT,
        selected_model: typing.Optional[DocExtractPageRequestSelectedModel] = OMIT,
        translation_source: typing.Optional[str] = OMIT,
        translation_target: typing.Optional[str] = OMIT,
        glossary_document: typing.Optional[str] = OMIT,
        avoid_repetition: typing.Optional[bool] = OMIT,
        num_outputs: typing.Optional[int] = OMIT,
        quality: typing.Optional[float] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        sampling_temperature: typing.Optional[float] = OMIT,
        response_format_type: typing.Optional[DocExtractPageRequestResponseFormatType] = OMIT,
        settings: typing.Optional[RunSettings] = OMIT,
        request_options: typing.Optional[RequestOptions] = None
    ) -> DocExtractPageResponse:
        """
        Parameters
        ----------
        documents : typing.Sequence[str]

        functions : typing.Optional[typing.Sequence[RecipeFunction]]

        variables : typing.Optional[typing.Dict[str, typing.Any]]
            Variables to be used as Jinja prompt templates and in functions as arguments

        variables_schema : typing.Optional[typing.Dict[str, VariableSchema]]
            Schema for variables to be used in the variables input

        sheet_url : typing.Optional[str]

        selected_asr_model : typing.Optional[DocExtractPageRequestSelectedAsrModel]

        language : typing.Optional[str]

        translation_model : typing.Optional[DocExtractPageRequestTranslationModel]

        google_translate_target : typing.Optional[str]
            use `translation_model` & `translation_target` instead.

        task_instructions : typing.Optional[str]

        selected_model : typing.Optional[DocExtractPageRequestSelectedModel]

        translation_source : typing.Optional[str]
            This is usually inferred from the spoken language, but in case that is set to Auto detect, you can specify one explicitly.

        translation_target : typing.Optional[str]

        glossary_document : typing.Optional[str]
            Provide a glossary to customize translation and improve accuracy of domain-specific terms.
            If not specified or invalid, no glossary will be used. Read about the expected format [here](https://docs.google.com/document/d/1TwzAvFmFYekloRKql2PXNPIyqCbsHRL8ZtnWkzAYrh8/edit?usp=sharing).

        avoid_repetition : typing.Optional[bool]

        num_outputs : typing.Optional[int]

        quality : typing.Optional[float]

        max_tokens : typing.Optional[int]

        sampling_temperature : typing.Optional[float]

        response_format_type : typing.Optional[DocExtractPageRequestResponseFormatType]

        settings : typing.Optional[RunSettings]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocExtractPageResponse
            Successful Response

        Examples
        --------
        import asyncio

        from gooey import AsyncGooey

        client = AsyncGooey(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.synthetic_data_maker_for_videos_pd_fs.doc_extract(
                documents=["documents"],
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/doc-extract",
            method="POST",
            json={
                "functions": functions,
                "variables": variables,
                "variables_schema": variables_schema,
                "documents": documents,
                "sheet_url": sheet_url,
                "selected_asr_model": selected_asr_model,
                "language": language,
                "translation_model": translation_model,
                "google_translate_target": google_translate_target,
                "task_instructions": task_instructions,
                "selected_model": selected_model,
                "translation_source": translation_source,
                "translation_target": translation_target,
                "glossary_document": glossary_document,
                "avoid_repetition": avoid_repetition,
                "num_outputs": num_outputs,
                "quality": quality,
                "max_tokens": max_tokens,
                "sampling_temperature": sampling_temperature,
                "response_format_type": response_format_type,
                "settings": settings,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(DocExtractPageResponse, parse_obj_as(type_=DocExtractPageResponse, object_=_response.json()))  # type: ignore
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(typing.Any, parse_obj_as(type_=typing.Any, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(HttpValidationError, parse_obj_as(type_=HttpValidationError, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(GenericErrorResponse, parse_obj_as(type_=GenericErrorResponse, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(FailedReponseModelV2, parse_obj_as(type_=FailedReponseModelV2, object_=_response.json()))  # type: ignore
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def async_doc_extract(
        self,
        *,
        documents: typing.Sequence[str],
        functions: typing.Optional[typing.Sequence[RecipeFunction]] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        variables_schema: typing.Optional[typing.Dict[str, VariableSchema]] = OMIT,
        sheet_url: typing.Optional[str] = OMIT,
        selected_asr_model: typing.Optional[DocExtractPageRequestSelectedAsrModel] = OMIT,
        language: typing.Optional[str] = OMIT,
        translation_model: typing.Optional[DocExtractPageRequestTranslationModel] = OMIT,
        google_translate_target: typing.Optional[str] = OMIT,
        task_instructions: typing.Optional[str] = OMIT,
        selected_model: typing.Optional[DocExtractPageRequestSelectedModel] = OMIT,
        translation_source: typing.Optional[str] = OMIT,
        translation_target: typing.Optional[str] = OMIT,
        glossary_document: typing.Optional[str] = OMIT,
        avoid_repetition: typing.Optional[bool] = OMIT,
        num_outputs: typing.Optional[int] = OMIT,
        quality: typing.Optional[float] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        sampling_temperature: typing.Optional[float] = OMIT,
        response_format_type: typing.Optional[DocExtractPageRequestResponseFormatType] = OMIT,
        settings: typing.Optional[RunSettings] = OMIT,
        request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncApiResponseModelV3:
        """
        Parameters
        ----------
        documents : typing.Sequence[str]

        functions : typing.Optional[typing.Sequence[RecipeFunction]]

        variables : typing.Optional[typing.Dict[str, typing.Any]]
            Variables to be used as Jinja prompt templates and in functions as arguments

        variables_schema : typing.Optional[typing.Dict[str, VariableSchema]]
            Schema for variables to be used in the variables input

        sheet_url : typing.Optional[str]

        selected_asr_model : typing.Optional[DocExtractPageRequestSelectedAsrModel]

        language : typing.Optional[str]

        translation_model : typing.Optional[DocExtractPageRequestTranslationModel]

        google_translate_target : typing.Optional[str]
            use `translation_model` & `translation_target` instead.

        task_instructions : typing.Optional[str]

        selected_model : typing.Optional[DocExtractPageRequestSelectedModel]

        translation_source : typing.Optional[str]
            This is usually inferred from the spoken language, but in case that is set to Auto detect, you can specify one explicitly.

        translation_target : typing.Optional[str]

        glossary_document : typing.Optional[str]
            Provide a glossary to customize translation and improve accuracy of domain-specific terms.
            If not specified or invalid, no glossary will be used. Read about the expected format [here](https://docs.google.com/document/d/1TwzAvFmFYekloRKql2PXNPIyqCbsHRL8ZtnWkzAYrh8/edit?usp=sharing).

        avoid_repetition : typing.Optional[bool]

        num_outputs : typing.Optional[int]

        quality : typing.Optional[float]

        max_tokens : typing.Optional[int]

        sampling_temperature : typing.Optional[float]

        response_format_type : typing.Optional[DocExtractPageRequestResponseFormatType]

        settings : typing.Optional[RunSettings]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncApiResponseModelV3
            Successful Response

        Examples
        --------
        import asyncio

        from gooey import AsyncGooey

        client = AsyncGooey(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.synthetic_data_maker_for_videos_pd_fs.async_doc_extract(
                documents=["documents"],
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v3/doc-extract/async",
            method="POST",
            json={
                "functions": functions,
                "variables": variables,
                "variables_schema": variables_schema,
                "documents": documents,
                "sheet_url": sheet_url,
                "selected_asr_model": selected_asr_model,
                "language": language,
                "translation_model": translation_model,
                "google_translate_target": google_translate_target,
                "task_instructions": task_instructions,
                "selected_model": selected_model,
                "translation_source": translation_source,
                "translation_target": translation_target,
                "glossary_document": glossary_document,
                "avoid_repetition": avoid_repetition,
                "num_outputs": num_outputs,
                "quality": quality,
                "max_tokens": max_tokens,
                "sampling_temperature": sampling_temperature,
                "response_format_type": response_format_type,
                "settings": settings,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(AsyncApiResponseModelV3, parse_obj_as(type_=AsyncApiResponseModelV3, object_=_response.json()))  # type: ignore
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(typing.Any, parse_obj_as(type_=typing.Any, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(HttpValidationError, parse_obj_as(type_=HttpValidationError, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(GenericErrorResponse, parse_obj_as(type_=GenericErrorResponse, object_=_response.json()))  # type: ignore
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def status_doc_extract(
        self, *, run_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DocExtractPageStatusResponse:
        """
        Parameters
        ----------
        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocExtractPageStatusResponse
            Successful Response

        Examples
        --------
        import asyncio

        from gooey import AsyncGooey

        client = AsyncGooey(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.synthetic_data_maker_for_videos_pd_fs.status_doc_extract(
                run_id="run_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v3/doc-extract/status", method="GET", params={"run_id": run_id}, request_options=request_options
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(DocExtractPageStatusResponse, parse_obj_as(type_=DocExtractPageStatusResponse, object_=_response.json()))  # type: ignore
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    typing.cast(typing.Any, parse_obj_as(type_=typing.Any, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    typing.cast(HttpValidationError, parse_obj_as(type_=HttpValidationError, object_=_response.json()))  # type: ignore
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(GenericErrorResponse, parse_obj_as(type_=GenericErrorResponse, object_=_response.json()))  # type: ignore
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
